// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qykkqekfpogtgsemzset.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5a2txZWtmcG9ndGdzZW16c2V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNzM2MzUsImV4cCI6MjA1NTY0OTYzNX0.NrdtMTiJ5wKbsyS27Q8Zl9ZkUro68c-atARzEK8K0PM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);